# Generated by Django 5.0.7 on 2024-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expereince',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
